name: Update GitHub Activity

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: jamesgeorge007/github-activity-readme@4aefbfa1c222d70537dc6a02f0519266aab2b1ea # master 2026-03-30
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: 'chore: update activity feed'
          MAX_LINES: 5
